# Generated by Django 5.0.14 on 2026-06-28 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
        ('inventory', '0002_cardcopy_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='card_copy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auctions', to='inventory.cardcopy'),
        ),
    ]
