# Generated by Django 5.0.14 on 2026-06-28 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_rarity'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardcopy',
            name='card_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='cards.cardimage'),
        ),
    ]
