# Generated by Django 5.0.14 on 2026-06-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('card_type', models.CharField(choices=[('LEADER', 'Leader'), ('CHARACTER', 'Character'), ('EVENT', 'Event'), ('STAGE', 'Stage')], max_length=12)),
                ('rarity', models.CharField(choices=[('C', 'Common'), ('UC', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super Rare'), ('SEC', 'Secret Rare'), ('L', 'Leader'), ('P', 'Promo')], max_length=5)),
                ('cost', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('life', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('attribute', models.CharField(blank=True, max_length=20)),
                ('power', models.PositiveIntegerField(blank=True, null=True)),
                ('counter', models.PositiveIntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, db_index=True, max_length=30)),
                ('block', models.CharField(blank=True, max_length=10)),
                ('feature', models.CharField(blank=True, max_length=255)),
                ('effect', models.TextField(blank=True)),
                ('set_name', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('alt_image', models.ImageField(blank=True, null=True, upload_to='cards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['card_id'],
            },
        ),
    ]
