# Generated by Django 5.0.14 on 2026-06-28 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='alt_image',
        ),
        migrations.RemoveField(
            model_name='card',
            name='image',
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cards/')),
                ('is_alternate', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cards.card')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('card', 'order')},
            },
        ),
    ]
