# Generated by Django 5.0.14 on 2026-06-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_remove_card_alt_image_remove_card_image_cardimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('C', 'Common'), ('UC', 'Uncommon'), ('R', 'Rare'), ('SR', 'Super Rare'), ('SEC', 'Secret Rare'), ('L', 'Leader'), ('P', 'Promo'), ('TR', 'Treasury Rare'), ('SP CARD', 'Special Card')], max_length=10),
        ),
    ]
